## Raw maetrials endpoints

### Get all materials
GET localhost:8080/api/v1/materials?page=0&size=10

### Get material by id
GET localhost:8080/api/v1/materials/6


### Create new material
POST localhost:8080/api/v1/materials
Content-Type: application/json

{
  "name": "LCD Screen 15 inch",
  "unit": "UNIT",
  "stock": 200,
  "stockMin": 50,
  "unitCost": 85.00,
  "supplierIds" : [1]
}

### update material


### delete material if has no order

