## Raw maetrials endpoints

### Get all materials
GET localhost:8080/api/v1/materials


### Create new material
POST localhost:8080/api/v1/materials
Content-Type: application/json

{
  "name": "Oak Wood",
  "stock": 150,
  "stockMin": 50,
  "unit": "kg",
  "supplierId": 1
}

