## Supplier order endpoitns

@host = localhost:8080/api/v1/supplier-orders

### Create supplier order
POST {{host}}/
Content-Type: application/json

{
  "supplierId": 1,
  "orderDate": "2025-11-01",
  "items": [
    {
      "materialId": 4,
      "quantity": 100,
      "unitPrice": 20
    }
  ]
}


### Get all orders
GET {{host}}?page=0&size=1
Content-Type: application/json


### Get order by id
GET {{host}}/18


### update order status
PUT {{host}}/18/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}