## Driver endpoints

@host = localhost:8080/api/v1

### Get all drivers
GET {{host}}/drivers

### Get driver by id
GET {{host}}/drivers/{driverId}

### Create a new driver
POST {{host}}/drivers
Content-Type: application/json

{
  "name": "John Doe",
  "licenseNumber": "D1234567",
  "phoneNumber": "555-1234"
}

### Update a driver by ID
PUT {{host}}/drivers/{driverId}
Content-Type: application/json

{
  "name": "Jane Smith",
  "licenseNumber": "D7654321",
  "phoneNumber": "555-5678"
}

### Delete a driver by ID
DELETE {{host}}/drivers/{driverId}

